"""Modelo de dados para os templates de filmes por gênero."""

MOVIES_BY_GENRE = {
    'acao': {
        'alerta-vermelho': 'generos_filmes/Ação/alertavermelho.html',
        'ate-o-ultimo-homem': 'generos_filmes/Ação/ultimohomen.html',
        'bad-boys': 'generos_filmes/Ação/badboys.html',
        'clube-da-luta': 'generos_filmes/Ação/clube_luta.html',
        'duro-de-matar': 'generos_filmes/Ação/durodematar.html',
        'exterminador': 'generos_filmes/Ação/exterminador.html',
        'gladiador': 'generos_filmes/Ação/gladiador.html',
        'john-wick': 'generos_filmes/Ação/johnwick.html',
        'madmax': 'generos_filmes/Ação/madmax.html',
        'mercenarios': 'generos_filmes/Ação/mercenarios.html',
        'missao-impossivel': 'generos_filmes/Ação/missaoimpossivel.html',
        'protetor': 'generos_filmes/Ação/protetor.html',
    },
    'comedia': {
        'as-branquelas': 'generos_filmes/Comedia/branquelas.html',
        'click': 'generos_filmes/Comedia/click.html',
        'deadpool': 'generos_filmes/Comedia/deadpool.html',
        'esposa-de-mentirinha': 'generos_filmes/Comedia/esposa.html',
        'ferias-frustradas': 'generos_filmes/Comedia/feriasfrustadas.html',
        'superbad': 'generos_filmes/Comedia/superbad.html',
        'gente-grande-2': 'generos_filmes/Comedia/gentegrande2.html',
        'debiloide': 'generos_filmes/Comedia/debiloide.html',
        'jojorabbit': 'generos_filmes/Comedia/jojorabbit.html',
        'virgem-aos-40': 'generos_filmes/Comedia/virgem40.html',
        '6-ridiculos': 'generos_filmes/Comedia/6ridiculos.html',
        'seguranca': 'generos_filmes/Comedia/segurança.html',
    },
    'animacao': {
        'noiva': 'generos_filmes/Animação/noiva.html',
        'castelo': 'generos_filmes/Animação/castelo.html',
        'coraline': 'generos_filmes/Animação/coraline.html',
        'era-do-gelo': 'generos_filmes/Animação/eradogelo.html',
        'spiderman': 'generos_filmes/Animação/spiderman.html',
        'kungfupanda': 'generos_filmes/Animação/kungfupanda.html',
        'lorax': 'generos_filmes/Animação/lorax.html',
        'incriveis': 'generos_filmes/Animação/incriveis.html',
        'ospequeninos': 'generos_filmes/Animação/ospequeninos.html',
        'poragua': 'generos_filmes/Animação/poragua.html',
        'ratatuli': 'generos_filmes/Animação/ratatuli.html',
        'upaltas': 'generos_filmes/Animação/upaltas.html',
    },
    'brasileiro': {
        'bacurau': 'generos_filmes/Braseleiro/bacurau.html',
        'areia': 'generos_filmes/Braseleiro/areia.html',
        'carandiru': 'generos_filmes/Braseleiro/carandiru.html',
        'central': 'generos_filmes/Braseleiro/central.html',
        'cidade-de-deus': 'generos_filmes/Braseleiro/cidadeDeus.html',
        'estomago': 'generos_filmes/Braseleiro/estomago.html',
        'maniaco': 'generos_filmes/Braseleiro/maniacoP.html',
        'mae-peca': 'generos_filmes/Braseleiro/maepeça.html',
        'palhaco': 'generos_filmes/Braseleiro/palhaço.html',
        'reflexoes': 'generos_filmes/Braseleiro/reflexoesL.html',
        'se-fosse-voce': 'generos_filmes/Braseleiro/sefossevc.html',
        'sonhos-roubados': 'generos_filmes/Braseleiro/sonhoroubados.html',
    },
    'ficcao': {
        'alien': 'generos_filmes/Ficção/alien.html',
        'bladerunner': 'generos_filmes/Ficção/bladerunner.html',
        'guardioes': 'generos_filmes/Ficção/guardioes.html',
        'harry': 'generos_filmes/Ficção/harry.html',
        'interstelar': 'generos_filmes/Ficção/interstelar.html',
        'jurasicpark': 'generos_filmes/Ficção/jurasicpark.html',
        'matrix': 'generos_filmes/Ficção/matrix.html',
        'piratas': 'generos_filmes/Ficção/piratas.html',
        'show': 'generos_filmes/Ficção/show.html',
        'star': 'generos_filmes/Ficção/star.html',
        'umdia': 'generos_filmes/Ficção/umdia.html',
        'uncharted': 'generos_filmes/Ficção/uncharted.html',
    },
    'romance': {
        'antesdeamanhecer': 'generos_filmes/Romance/antesdeamanhecer.html',
        'azul': 'generos_filmes/Romance/Azuleacormaisquente.html',
        'comoperderumhomem': 'generos_filmes/Romance/comoperderumhomem.html',
        'diariopaixao': 'generos_filmes/Romance/diariopaixão.html',
        'docenovembro': 'generos_filmes/Romance/docenovembro.html',
        'iloveyou': 'generos_filmes/Romance/iloveyou.html',
        'lembrancas': 'generos_filmes/Romance/lembranças.html',
        'naturezaselvagem': 'generos_filmes/Romance/naturezaselvagem.html',
        'orgulhopreconceito': 'generos_filmes/Romance/orgulho&preconceito.html',
        'pacienteingles': 'generos_filmes/Romance/pacienteingles.html',
        'retrato': 'generos_filmes/Romance/retrato.html',
    },
    'terror': {
        'abruxa': 'generos_filmes/terror/abruxa.html',
        'entidade': 'generos_filmes/terror/entidade.html',
        'paranormal': 'generos_filmes/terror/paranormal.html',
        'corra': 'generos_filmes/terror/corra.html',
        'hereditario': 'generos_filmes/terror/hereditario.html',
        'invocacao': 'generos_filmes/terror/invocaçaõ.html',
        'it': 'generos_filmes/terror/it.html',
        'mama': 'generos_filmes/terror/mama.html',
        'massacre': 'generos_filmes/terror/massacre.html',
        'chuck': 'generos_filmes/terror/chuck.html',
        'exorcita': 'generos_filmes/terror/exorcita.html',
        'iluminado': 'generos_filmes/terror/iluminado.html',
    },
}
